libkrun: fix send_command_over_stream() call arguments
Root Cause Analysis:
- The function send_command_over_stream() takes 8 arguments:
  (cmd_parts, io_mode, vm_keep_timeout_secs, extend_timeout_secs,
   env_vars, cwd, stdin, stream)
- The call site passed 9 arguments with an extra bool
  daemon_keep_timeout.is_some() as the 3rd parameter
- This was a leftover from a previous API that accepted bool

Solution:
- Remove the extra bool argument from both Windows and non-Windows
  function calls (send_command_over_named_pipe and
  send_command_over_stream)
- Add #[allow(unused_imports)] for discover_vm_session export
  which is conditionally compiled for Linux without libkrun feature

Fixes: make
error[E0308]: mismatched types: expected `&str`, found `&HashMap`
error[E0061]: this function takes 8 arguments but 9 arguments were supplied

Signed-off-by: Wu Fengguang <wfg@mail.ustc.edu.cn>