io: improve error message for env config loading
Problem: Panic message was confusing when env config file not found:
  Failed to deserialize env config:
     0: Environment config file not found: '/home/wfg/.epkg/envs/xxx/etc/epkg/env.yaml'

Solution:
- io.rs: show path and original io/yaml error on line 1
- io.rs: add hint "Environment 'xxx' may not exist" only when NotFound
- models.rs: use unwrap_or_else() instead of expect() to exit cleanly

New output:
  Error: /home/wfg/.epkg/envs/xxx/etc/epkg/env.yaml: No such file or directory (os error 2)
    Environment 'xxx' may not exist

Signed-off-by: Wu Fengguang <wfg@mail.ustc.edu.cn>